### ISSUE TITLE
question

### ISSUE THREAD

**Issue by cymqqqq** [Hoff97/tensorjs#32]
The relationship between the src and the lib directory?

**Comment by Hoff97** [comment]
Hi,
the `src` directory contains the implementation of the WASM backend in rust. The lib directory contains the actual library implemented in typescript.
During the build, the Output of the Rust build is copied into the lib/wasm directory, where its then used by the library.

**Comment by cymqqqq** [comment]
Awesome! good job :)
You implement my idea, so what will you implement in the next step for the WASM backend?

**Comment by Hoff97** [comment]
There are a few things that the WASM backend definitely needs:
- Optimized implementations: The convolution operation for example is implemented pretty naively and thus not very usable at the moment
- Maybe some support for other datatypes (eg. half precision float, int, long and so on)
- The WASM backend would be a lot faster if it were run on multiple service workers instead of the main thread - although that would require a lot more coordination between workers, so its probably not so easy

Of course, more operators are also always nice, for this I mostly follow the onnx operators (https://github.com/onnx/onnx/blob/master/docs/Operators.md).

**Comment by cymqqqq** [comment]
OK, THX, I will go deep with that in my spare time.
Another question: what do you think that the WASM backend you wrote will be applied for?

**Comment by Hoff97** [comment]
I think there are two use cases:
- When you deal with not so large tensors, the overhead of WebGL might be so large that WASM is actually faster
- On devices where WebGL is not available (or only through software rendering), WASM might be a good fallback
